# Generated by Django 5.0.4 on 2024-04-13 11:56

import acadify.api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(max_length=255, upload_to=acadify.api.utils.UploadUtils.attachment),
        ),
    ]
